import {Client} from './_models/client';

export const CLIENTS: Client[] = [
    {
        id: 1,
        companyName: 'PATIO Restaurant',
        contactName: 'Mark Ferrari',
        email: 'markferrari@me.com',
        address1: '328 Commercial Street',
        address2: '',
        address3: '',
        city: 'Provincetown',
        state: 'MA',
        zipCode: '02657',
        phone1: '',
        phone2: '',
        fax1: '',
        fax2: ''
    },
    {
        id: 2,
        companyName: 'World Elite Concierge',
        contactName: 'Tanya Draskovic',
        email: 'worldeliteconcierge@gmail.com',
        address1: '142 Royal Palm Way',
        address2: '',
        address3: '',
        city: 'Boca Raton',
        state: 'FL',
        zipCode: '33432',
        phone1: '407-818-0070',
        phone2: '',
        fax1: '',
        fax2: ''
    },
    {
        id: 3,
        companyName: 'SONY Music Entertainment',
        contactName: 'Clive Davis',
        email: 'mariela.bradford@sonymusic.com',
        address1: '25 MADISON AVENUE – 22nd Floor',
        address2: '',
        address3: '',
        city: 'New York',
        state: 'NY',
        zipCode: '10010',
        phone1: '212-818-0070',
        phone2: '',
        fax1: '',
        fax2: ''
    },
    {
        id: 4,
        companyName: 'We Are Alexander',
        contactName: 'Rashad Barr',
        email: 'mariela.bradford@sonymusic.com',
        address1: '1125 Trenton-Harbourton Road',
        address2: 'Suite 200',
        address3: '',
        city: 'Titusville',
        state: 'NJ',
        zipCode: '08560',
        phone1: '(609) 730.7990',
        phone2: '(609) 730.7991',
        fax1: '(609) 730.7992',
        fax2: '(609) 730.7993'
    },
    {
        id: 5,
        companyName: 'Rave-Nation',
        contactName: 'Shawhwwn Amirkhizi',
        email: 'sales@tryptixfashion.com',
        address1: '1595 State Highway 150',
        address2: 'Suite C',
        address3: '',
        city: 'Evanston',
        state: 'WY',
        zipCode: '82930',
        phone1: '',
        phone2: '',
        fax1: '',
        fax2: ''
    },
    {
        id: 6,
        companyName: 'Wieden & Kennedy',
        contactName: 'Ashley Mehall',
        email: 'ashley.mehall@wk.com',
        address1: '150 Varick Street',
        address2: '',
        address3: '',
        city: 'New York',
        state: 'WY',
        zipCode: '10013',
        phone1: '',
        phone2: '',
        fax1: '',
        fax2: ''
    },
]
